/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class GroceryCounterTest {
  // Test the initial state of the counter
  @Test
  public void testInitialState() {
    GroceryCounter gc = new GroceryCounter();
    assertEquals("00.00", gc.total());
    assertEquals(0, gc.overflows());
  }

  // Test incrementing hundredths
  @Test
  public void testHundredthsIncrement() {
    GroceryCounter gc = new GroceryCounter();
    gc.hundredths();
    assertEquals("00.01", gc.total());
  }

  // Test hundredths rolling over to tenths
  @Test
  public void testHundredthsCarryToTenths() {
    GroceryCounter gc = new GroceryCounter();
    for (int i = 0; i < 10; i++) {
      gc.hundredths();
    }
    assertEquals("00.10", gc.total());
  }

  // Test tenths rolling over to ones
  @Test
  public void testTenthsCarryToOnes() {
    GroceryCounter gc = new GroceryCounter();
    for (int i = 0; i < 10; i++) {
      gc.tenths();
    }
    assertEquals("01.00", gc.total());
  }

  // Test incrementing tens
  @Test
  public void testOnesCarryToTens() {
    GroceryCounter gc = new GroceryCounter();
    for (int i = 0; i < 10; i++) {
      gc.ones();
    }
    assertEquals("10.00", gc.total());
  }

  // Test tens rolling over to zero and incrementing overflow
  @Test
  public void testTensOverflow() {
    GroceryCounter gc = new GroceryCounter();
    for (int i = 0; i < 10; i++) {
      gc.tens();
    }
    assertEquals("00.00", gc.total());
    assertEquals(1, gc.overflows());
  }
  
  // Test full roll over from 9999 to 0000
  @Test
  public void testFullRollOverFromHundredths() {
    GroceryCounter gc = new GroceryCounter();
    for (int i = 0; i < 10000; i++) {
      gc.hundredths();
    }
    assertEquals("00.00", gc.total());
    assertEquals(1, gc.overflows());
  }

  // Test clearing the counter
  @Test
  public void testClear() {
    GroceryCounter gc = new GroceryCounter();
    gc.hundredths();
    gc.tenths();
    gc.ones();
    gc.tens();
    gc.clear();
    assertEquals("00.00", gc.total());
    assertEquals(0, gc.overflows());
  }
}
